import Head from 'next/head'
import { useEffect, useState } from 'react'
import styles from '../styles/Home.module.css'

export default function Home() {
  const [date, setDate] = useState("");

  useEffect(() => {
    const dateNow = new Date().toLocaleDateString();
    setDate(dateNow);
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>Hello IZagro</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          {date}
        </h1>
      </main>
      
    </div>
  )
}